package wtom.model.domain.util;

public enum RecursoAcao {

    USUARIO_CRIAR,
    USUARIO_VISUALIZAR,
    USUARIO_EDITAR,
    USUARIO_EXCLUIR,

    OLIMPIADA_CRIAR,
    OLIMPIADA_VISUALIZAR,
    OLIMPIADA_EDITAR,
    OLIMPIADA_EXCLUIR,

    INSCRICAO_REALIZAR,
    INSCRICAO_VISUALIZAR,
    INSCRICAO_EDITAR,
    INSCRICAO_CANCELAR,

    PREMIACAO_REGISTRAR,
    PREMIACAO_VISUALIZAR,
    PREMIACAO_EDITAR,
    PREMIACAO_REMOVER,

    AVISO_CRIAR,
    AVISO_VISUALIZAR,
    AVISO_EDITAR,
    AVISO_EXCLUIR,

    FORUM_CRIAR_POST,
    FORUM_VISUALIZAR,
    FORUM_EDITAR_POST,
    FORUM_EXCLUIR_POST,

    CONTEUDO_CRIAR,
    CONTEUDO_VISUALIZAR,
    CONTEUDO_EDITAR,
    CONTEUDO_EXCLUIR,

    EVENTO_CRIAR,
    EVENTO_VISUALIZAR,
    EVENTO_EDITAR,
    EVENTO_EXCLUIR,

    NOTIFICACAO_GERENCIAR,
    NOTIFICACAO_VISUALIZAR
}
